<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function capable_help($path, $arg) {
  switch ($path) {
    case "help.page.capable":
      return '' . t("You have sucessfully added a hook into your custom Capable module!") . '';
      break;
  }
}

// Load main library to all pages with hook_page_attachments
function capable_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'capable/main';
}


/** To attach a library to a certain existing '#type',
* for all instances of it, we use hook_element_info_alter():
*/
function capable_element_info_alter(array &$types) {
  if (isset($types['select'])) {
    $types['select']['#attached']['library'][] = 'capable/miscellaneous';
  }
}

function capable_theme() {
   $theme['welcome_page'] = [
       'template' => 'welcome',
   ];
   return $theme;
};
